version: "3.3"
services:
  db:
    container_name: backend_db
    restart: always
    image: backend_db
    build:
      context: ./db
    volumes:
      - db:/var/lib/postgresql/data
    env_file:
      - ./.env.local
    networks:
      - network
    ports:
      - 5432:5432

  graphql:
    container_name: backend_graphql
    restart: always
    image: backend_graphql
    build:
      context: ./graphql
    env_file:
      - ./.env.local
    depends_on:
      - db
    networks:
      - network
    ports:
      - 5433:5433
    command: >
      --connection "${DATABASE_URL}"
      --port 5433
      --schema website
      --default-role user_login
      --append-plugins postgraphile-plugin-connection-filter
      --jwt-token-identifier website.jwt_token
      --jwt-secret "${JWT_SECRET}"

networks:
  network:

volumes:
  db:
