#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

branch="$(git rev-parse --abbrev-ref HEAD)"
protected_branch="main"
policy="[POLICY]: commit is blocked in this branch. Never commit code directly to $protected_branch!"

if [ "$branch" = "$protected_branch" ]; then
  printf "%s\n" "$policy"
  exit 1
else
  npm run lint && npm run format
fi
